//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public string MaChamCong { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Nam { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
