//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoCa
    {
        public int MaPhanCa { get; set; }
        public int MaCa { get; set; }
        public decimal SoTienThuDuoc { get; set; }
        public decimal SoTienCatGiu { get; set; }
        public Nullable<decimal> SoTienBanGiao { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual PhanCa PhanCa { get; set; }
    }
}
