//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
            this.PhieuNhapHangChiTiets = new HashSet<PhieuNhapHangChiTiet>();
            this.PhieuTraHangChiTiets = new HashSet<PhieuTraHangChiTiet>();
        }
    
        public string MaHH { get; set; }
        public string TenHang { get; set; }
        public string MaNH { get; set; }
        public string XuatXu { get; set; }
        public System.DateTime NgaySanXuat { get; set; }
        public System.DateTime HanSuDung { get; set; }
        public decimal GiaNhap { get; set; }
        public decimal GiaBan { get; set; }
        public string DonViTinh { get; set; }
        public string NhaCungCap { get; set; }
        public string MaVach { get; set; }
        public int DinhMuc { get; set; }
        public int Soluong { get; set; }
        public bool TrangThaiBan { get; set; }
        public decimal VAT { get; set; }
    
        public virtual NhaCungCap NhaCungCap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapHangChiTiet> PhieuNhapHangChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuTraHangChiTiet> PhieuTraHangChiTiets { get; set; }
        public virtual NhomHang NhomHang { get; set; }
    }
}
