//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
        }
    
        public string SoHD { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public string MaKH { get; set; }
        public decimal VAT { get; set; }
        public string HinhThucThanhToan { get; set; }
        public Nullable<decimal> TienKhachDua { get; set; }
        public Nullable<decimal> TienGuiKhach { get; set; }
        public Nullable<decimal> TongTienKM { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public int MaPos { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
        public virtual MayPos MayPos { get; set; }
    }
}
