//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaKM { get; set; }
        public string MaLyDo { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string MaHH { get; set; }
        public string MaNV { get; set; }
    
        public virtual DanhSachKhuyenMai DanhSachKhuyenMai { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
