//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHangChiTiet
    {
        public string MaHangNhap { get; set; }
        public string SoPhieu { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
        public decimal VAT { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuNhapHang PhieuNhapHang { get; set; }
    }
}
